/*
TO DO
    ARREGLO DE POSTS. 
        STRUCT POST (ID, CREADOR, CONTENIDO, ABB LIKES)
    HASH DE USUARIOS
        STRUCT USUARIO (NOMBRE, HEAP DE POSTS SIN VER TODAVÍA)
    
FUNCIONES QUE DEBE TENER
    LOGIN
    LOGOUT
    PUBLICAR POST
    VER PROX POST
    LIKEAR POST POR ID
    MOSTRAR LIKE DE POST POR ID
*/


void esperar_orden(){
    // GETLINE. RECIBIR COMANDO
    // METER COMANDO EN SWTICHCASE Y EJECUTAR FUNCION CORRESPONDIENTE
    // LOOP HASTA QUE EL USUARIO LLAME A QUIT
    return;
}


int main(ARCHIVO CON USUARIOS){
    // CHECHEAR NUMERO DE INGRESOS CORRECTO
    // ASEGURARSE QUE EL ARCHIVO EXISTA Y SE PUEDA LEER
    // SACAR USUARIOS DEL ARCHIVO Y CREAR LOS USUARIOS

    // LLAMAR FUNCION LOOP ESPERAR ORDEN

    // VOLVER AQUI CUANDO SE LLAME A QUIT EN esperar_orden. ELIMINAR TODAS LAS ESTRUCTURAS, LIBERAR MEMORIA
    return 0;
}